name: QA

on:
  push:
    branches: [ "QA" ]
  pull_request:
    branches: [ "QA" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Run a one-line script
        run: echo Usando a Branch de QA
